# Generated by Django 3.2.7 on 2021-10-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happenings', '0004_alter_event_host'),
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(to='happenings.Event'),
        ),
    ]
