# Generated by Django 3.2.7 on 2021-10-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happenings', '0005_auto_20211011_1506'),
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='swiped_events',
            field=models.ManyToManyField(to='happenings.Schedule'),
        ),
    ]
