# Generated by Django 3.2.7 on 2021-10-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_user_interests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='interests',
            new_name='interested_events',
        ),
    ]
