# Generated by Django 3.2.7 on 2021-11-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happenings', '0009_auto_20211103_1023'),
        ('authenticate', '0003_alter_user_interested_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interested_events',
            field=models.ManyToManyField(blank=True, related_name='users', to='happenings.Schedule'),
        ),
    ]
