# Generated by Django 3.2.7 on 2021-10-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happenings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='author',
            new_name='host',
        ),
    ]
