# Generated by Django 3.2.7 on 2021-10-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happenings', '0005_auto_20211011_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='interest_categories',
            field=models.ManyToManyField(blank=True, to='happenings.InterestCategory'),
        ),
        migrations.AlterField(
            model_name='event',
            name='requirement_categories',
            field=models.ManyToManyField(blank=True, to='happenings.RequirementCategory'),
        ),
    ]
