# Generated by Django 3.2.7 on 2021-10-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happenings', '0006_auto_20211016_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestcategory',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='requirementcategory',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
