# Generated by Django 3.2.7 on 2021-10-25 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happenings', '0006_alter_event_host'),
        ('happenings', '0007_auto_20211018_1252'),
    ]

    operations = [
    ]
