# Generated by Django 3.2.7 on 2021-11-03 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('happenings', '0008_merge_0006_alter_event_host_0007_auto_20211018_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedShortDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='admin_approved',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('N', 'Disapproved'), ('D', 'Deleted')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.user'),
        ),
        migrations.AddField(
            model_name='event',
            name='generated_short_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='happenings.generatedshortdescriptions'),
        ),
    ]
