# Generated by Django 3.2.7 on 2021-11-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happenings', '0009_auto_20211103_1023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequirementCategory',
            new_name='AccessibilityTags',
        ),
        migrations.RenameModel(
            old_name='InterestCategory',
            new_name='EventCategory',
        ),
        migrations.RemoveField(
            model_name='event',
            name='interest_categories',
        ),
        migrations.RemoveField(
            model_name='event',
            name='requirement_categories',
        ),
        migrations.AddField(
            model_name='event',
            name='accessibility_tags',
            field=models.ManyToManyField(blank=True, to='happenings.AccessibilityTags'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_categories',
            field=models.ManyToManyField(blank=True, to='happenings.EventCategory'),
        ),
    ]
