# Generated by Django 3.2.7 on 2021-11-05 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happenings', '0010_auto_20211105_1203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessibilityTags',
            new_name='AccessibilityTag',
        ),
    ]
